application: make-school-news
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# FAVICON
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

# STATIC DIRECTORIES
- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

# CRON SCRIPT
- url: /cron/.*
  script: cron.app
  login: admin

# INTERACTIVE CONSOLE
- url: /admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin

# MAIN SCRIPT
- url: .*
  script: app.app

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"
- name: pycrypto
  version: "2.6"